# -*- coding: utf-8 -*-
"""
TAB Score Viewer - Universal Guitar TAB Score Viewer Package

万能吉他谱查看器主包
"""

from .constants import (
    CONFIG_FILE,
    ANNOTATION_DIR,
    CUSTOM_THEMES_DIR,
    ANNOTATION_EXT,
    SUPPORTED_IMAGE_EXTENSIONS,
    SUPPORTED_PDF_EXTENSIONS,
    SUPPORTED_GTP_EXTENSIONS,
    SUPPORTED_ALL_EXTENSIONS,
    THEME_DARK,
    THEME_LIGHT,
    THEME_COLORS,
    _RENDER_PARAMS,
    _DEFAULT_GTP_FONT,
    _DEFAULT_LANGUAGE,
    _DEFAULT_THEME,
    _APP_BASE_DIR,
    ICON_PATH,
)

__all__ = [
    "CONFIG_FILE",
    "ANNOTATION_DIR",
    "CUSTOM_THEMES_DIR",
    "ANNOTATION_EXT",
    "SUPPORTED_IMAGE_EXTENSIONS",
    "SUPPORTED_PDF_EXTENSIONS",
    "SUPPORTED_GTP_EXTENSIONS",
    "SUPPORTED_ALL_EXTENSIONS",
    "THEME_DARK",
    "THEME_LIGHT",
    "THEME_COLORS",
    "_RENDER_PARAMS",
    "_DEFAULT_GTP_FONT",
    "_DEFAULT_LANGUAGE",
    "_DEFAULT_THEME",
    "_APP_BASE_DIR",
    "ICON_PATH",
]